### ISSUE TITLE
Build checkout fails on executors 11 and 13

### ISSUE THREAD

**Issue by vreynolds** [CircleCI-Public/cimg-openjdk#102]
Our builds started failing suddenly on executors 11 and 13 (8 still works fine) with the following error at `checkout`:

```
Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository
```

They worked ~ 2hrs ago, just before the latest batch of releases 🕵️‍♀️

**Comment by rzaaeeff** [comment]
Same here, SSH or Git client were removed image by accident.
![image](https://user-images.githubusercontent.com/7134001/134769623-0c795ca9-9896-4dcf-aa97-aa4f3e679fd4.png)

I think, this has been caused by #99.

**Comment by felicianotech** [comment]
Determined the issue. This is caused by the inclusion of sbt in recent images. A fix should be rolling out soon.

**Comment by felicianotech** [comment]
Hey @vreynolds, @rzaaeeff, or any of the +1s. This issue has been fixed and published. Can any of you confirm that it's actually fixed for you?

**Comment by rzaaeeff** [comment]
> Hey @vreynolds, @rzaaeeff, or any of the +1s. This issue has been fixed and published. Can any of you confirm that it's actually fixed for you?

Hi @felicianotech, we couldn't wait until the patch, and changed the base images. So, can't confirm right now.

**Comment by vreynolds** [comment]
@felicianotech fixed now, thank you! 🙏

**Comment by felicianotech** [comment]
Great! Thanks for the confirmation.
