### ISSUE TITLE
docker image 11.0 should match 11.0.11 instead of 11.0.0

### ISSUE THREAD

**Issue by clakech** [CircleCI-Public/cimg-openjdk#104]
The docker image cimg/openjdk:11.0 should match 11.0.12 instead of 11.0.0 right ?

![image](https://user-images.githubusercontent.com/1169286/134895311-c7253ee6-3a76-48f6-9a5e-d7a1e1abd4c6.png)

![image](https://user-images.githubusercontent.com/1169286/134895397-161d9c7f-37d8-4cb1-85a8-99ba95ca473f.png)

![image](https://user-images.githubusercontent.com/1169286/134895441-f11af0cc-a553-49bd-8dc5-f160317c41dd.png)

Documentation:
![image](https://user-images.githubusercontent.com/1169286/134895504-906ff20b-0a71-4366-bd81-17b70d5cc4c4.png)

**Comment by felicianotech** [comment]
Correct, this is a bug. This will be fixed shortly in #105.

**Comment by felicianotech** [comment]
The alias tags have been updated and point to the latest patch release, like they're suppose to.
