### ISSUE TITLE
OpenJDK 17.0.2 released

### ISSUE THREAD

**Issue by arielcarrera** [CircleCI-Public/cimg-openjdk#120]
OpenJDK 17.0.1 has some issues with the popular library lombok solved in OpenJDK 17.0.2
When do you plan to provide an image based on OpenJDK 17.0.2?

**Comment by felicianotech** [comment]
We use the packing provided by Adoptium. When they have a package available, we can build a release. We can keep this Issue open until that happens.

ref: https://adoptium.net/archive.html

**Comment by JalexChen** [comment]
Hi @arielcarrera - the package was uploaded today and waiting on a review from the team to merge. Closing this out.
