### ISSUE TITLE
Add JDK 20 and 19

### ISSUE THREAD

**Issue by jonatan-ivanov** [CircleCI-Public/cimg-openjdk#134]
They were released a while ago, I guess users would use it (I definitely would).

**Comment by felicianotech** [comment]
Hey. We build OpenJDK as provided by Adoptium. v19 is available now but not 20. We have a PR open for v19.0.0 right now: https://github.com/CircleCI-Public/cimg-openjdk/pull/136 This will be merged in the near future.

Once that is out, we will roll out the patch release (v19.0.1).
