### ISSUE TITLE
Python version in cimg/openjdk:11.0

### ISSUE THREAD

**Issue by HUSTluoqingqing** [CircleCI-Public/cimg-openjdk#137]
Why are you upgrading your python version in cimg/openjdk:11.0?

**Comment by felicianotech** [comment]
We're not. Recent Convenience Images are now built with Ubuntu 22.04. The default Python version is different between these Ubuntu versions. We don't install Python in this image, it just happens to be inherited from the base image., If you need a specific version, I'd suggest installing it or creating a custom image.

That being said, we won't be doing another Ubuntu version change until 2024 (the next LTS) so the Python major and minor version will the same until then.
