### ISSUE TITLE
Add openjdk 20

### ISSUE THREAD

**Issue by MohammadHoseini96** [CircleCI-Public/cimg-openjdk#149]
Java 20 has been released and has binaries available for OpenJDK 14. We would like to upgrade our build image to one with JDK 20.

**Comment by ryanbourdais** [comment]
Hi @MohammadHoseini96 I just opened a PR for an OpenJDK 20 image, hopefully it will be merged in and live by end of day tomorrow.

**Comment by ryanbourdais** [comment]
An Image for openjdk 20.0.1 just got merged and released so I will be closing this issue.
