### ISSUE TITLE
Feature Request: Add Mill build tool for Scala

### ISSUE THREAD

**Issue by nightscape** [CircleCI-Public/cimg-openjdk#155]
**Describe the Feature Request**
[Mill](http://mill-build.com/) is a modern alternative to SBT in the Scala world. It would be great to have it installed in the `cimg/openjdk` base image.

**Is your feature request related to a particular problem?**
I would like to switch a project using CircleCI over from SBT to Mill. The current SBT version is using `cimg/openjdk:18.0.1`. In order to be able to run the new Mill build, I'd need to have the `mill` executable available, and adapting `cimg/openjdk` would be one way where other people could benefit as well. 

**How will this feature request benefit CircleCI jobs using this image?**
It would speed up jobs using Mill significantly by not having to install Mill on every run?

> In order for us to add a tool within the image, it has to be something that is maintained and useful to a majority of CircleCI users. > Every tool added makes the image larger and slower for all users, so any new additions need to be carefully thought out.
I agree and would totally understand if you saw the downsides as exceeding the upside 😉 

**Describe the solution you would like to see**
I would like to see Mill package installed by default in the image.

**Describe alternatives you have considered**
Creating a special Scala & Mill Orb that uses [my Mill base image](https://hub.docker.com/r/nightscape/scala-mill/).

**Comment by ryanbourdais** [comment]
I dont see a problem with adding this to the image @BytesGuy, do you have any input? If not, I can open a PR today to add it to the `dockerfile.template` so it starts being rolled out in the next releases

**Comment by BytesGuy** [comment]
@ryanbourdais Mill seems a popular enough project that it’s worth consideration. As long as it doesn’t substantially increase the image size then it should be fine

**Comment by ryanbourdais** [comment]
@nightscape mill will be included in the java 21 release here: [#167 ](#167 )
