### ISSUE TITLE
Feature Request: Support Java 21

### ISSUE THREAD

**Issue by adambom** [CircleCI-Public/cimg-openjdk#161]
**Describe the Feature Request**
Java 21 became GA yesterday. Could you please add support for Java 21?

**Is your feature request related to a particular problem?**
Unable to easily build Java 21 projects using convenence images

**How will this feature request benefit CircleCI jobs using this image?**
Will allow Java 21 builds without the overhead of manually installing Java

**Describe the solution you would like to see**
A convenience image for OpenJDK 21

**Describe alternatives you have considered**
Manual installation in each job.

**Comment by bc-tayvs** [comment]
There is no stable java 21 version from Temurin but there are some nightly beta versions. Based on the latest nightly version and already existing java 20 Dockerfiles I have created a fork with implementation for java 21.

https://github.com/CircleCI-Public/cimg-openjdk/compare/main...bc-tayvs:cimg-openjdk:jdk21

**Comment by adambom** [comment]
Oh I see. "GA" really is depending on which distribution you're looking at. I'll wait patiently until temurin gets a release out.

In the meantime, we are able to make use of [this orb](https://circleci.com/developer/orbs/orb/joshdholtz/sdkman) to install the 21-open version in our jobs.

**Comment by exoego** [comment]
Official Release of jdk-21+35 is out: https://github.com/adoptium/temurin21-binaries/releases/tag/jdk-21%2B35

**Comment by dylanbaroody** [comment]
Would also appreciate this!

**Comment by xbrett** [comment]
This would really help out!

**Comment by adambom** [comment]
Official PR now open: https://github.com/CircleCI-Public/cimg-openjdk/pull/167
