### ISSUE TITLE
Bug Report: openjdk 21 image cannot checkout code

### ISSUE THREAD

**Issue by malteo** [CircleCI-Public/cimg-openjdk#169]
**Describe the bug**
`Checkout code` step fails on new `cimg/openjdk:21.0` image, instead it displays this error:

    Directory (/home/circleci/project) you are trying to checkout to is not empty and not a git repository

It looks like the recent addition of `mill` is the culprit, as it was for `sbt` in #102.

**Expected behavior**
Code should be checked out in `~/project`, which should be an empty dir.

**Workarounds**
Not a workaround, but maybe https://github.com/CircleCI-Public/cimg-shared/issues/40 should be bumped.

**Comment by JalexChen** [comment]
Looks like this was addressed with a re-release in #173 Closing this out, but let us know if you run into any issues
