### ISSUE TITLE
Feature Request: OpenJDK 22/23 images

### ISSUE THREAD

**Issue by shakuzen** [CircleCI-Public/cimg-openjdk#205]
**Describe the Feature Request**
cimg/openjdk has no images with OpenJDK 22 or later versions. OpenJDK 23 has gone GA recently.

**How will this feature request benefit CircleCI jobs using this image?**
Without JDK 22 and JDK 23 images, users wanting to compile/run their build with those JDK versions need to make their own build image or download and install the version of the JDK, which makes builds longer and uses more bandwidth than using a common convenience image.

**Describe the solution you would like to see**
OpenJDK 22 and OpenJDK 23 images.

**Describe alternatives you have considered**
As mentioned above, creating a custom image or downloading the JDK as part of the build are alternatives, but it would be nicer to have an official convenience image that already has the desired JDK version available in it.

**Comment by evant** [comment]
The macos runners go from jdk version 17 to 22 to 23 so not having this is an issue if you are trying to match versions between the two.

**Comment by bjohnso5** [comment]
#216 adds 22.0(.2) and 23.0 openjdk images. Apologies for the wait!
