### ISSUE TITLE
JDK 14 image

### ISSUE THREAD

**Issue by shakuzen** [CircleCI-Public/cimg-openjdk#39]
Java 14 has been released and [AdoptOpenJDK](https://adoptopenjdk.net/) has binaries available for OpenJDK 14. We would like to upgrade our build image to one with JDK 14, and we're currently using this build image.

**Comment by felicianotech** [comment]
Thanks for reaching out!

The OpenJDK v14 image should be available soon.

**Comment by felicianotech** [comment]
It was available as of about 45 minutes ago.
