### ISSUE TITLE
EA images

### ISSUE THREAD

**Issue by shakuzen** [CircleCI-Public/cimg-openjdk#53]
OpenJDK has Early Access (EA) builds available at jdk.java.net (e.g. currently JDK 15: https://jdk.java.net/15/). Having a CircleCI image available for those EA builds would allow us to more easily run our build on the EA version and give feedback before the final release.

**Comment by felicianotech** [comment]
We're not ready to have EA builds just yet but stable OpenJDK v15 is available.
