### ISSUE TITLE
Add -browsers variant

### ISSUE THREAD

**Issue by kool79** [CircleCI-Public/cimg-openjdk#54]

**Comment by felicianotech** [comment]
We have a beta available: https://discuss.circleci.com/t/next-gen-convenience-image-browsers-variant-beta/37794?u=felicianotech

**Comment by apupier** [comment]
It seems that there are browsers variant available now https://hub.docker.com/r/cimg/openjdk/tags?page=1&ordering=last_updated&name=browsers and one link to a specific one https://hub.docker.com/layers/cimg/openjdk/16.0-browsers/images/sha256-e78fcfe8c15eb0bb99d95526933c0189f5718a35d74461ad69cab5ca84440727?context=explore )
