### ISSUE TITLE
Upgrade to Gradle 6.7.0?

### ISSUE THREAD

**Issue by devkanro** [CircleCI-Public/cimg-openjdk#67]
There are some special reasons for stoping to upgrade the Gradle?
It seems the Gradle component has a long time not to upgrade...

**Comment by felicianotech** [comment]
Hi. I will create a PR for Gradle 6.7.0 however I would like to point out, the Gradle version this repository points to is not that old: https://github.com/CircleCI-Public/cimg-openjdk/blob/master/Dockerfile.template#L31

The way next-gen CircleCI Convenience Images work, once an image is created, it is not updated again. So whatever version of Gradle is installed in an image when it's created, that the version it will have. It will not be updated.

I hope this information helps. Please let me know if you have further questions on this.

**Comment by felicianotech** [comment]
Three new releases are publishing right now and will be available shortly. All three will have Gradle v6.7:

- cimg/openjdk:8.0.272
- cimg/openjdk:11.0.9
- cimg/openjdk:15.0.1
