### ISSUE TITLE
Add OpenJ9 images

### ISSUE THREAD

**Issue by jonatan-ivanov** [CircleCI-Public/cimg-openjdk#78]
[OpenJ9](https://www.eclipse.org/openj9/) is a popular JVM and CircleCI users would definitely benefit from it as it was [requested earlier](https://discuss.circleci.com/t/create-a-circleci-openjdk-convenience-image-based-on-eclipse-openj9/29504).

Providing OpenJ9 images would be a nice feature for framework/library maintainers who need to test their build against OpenJ9. GitHub Actions currently support AdoptOpenJDK builds including Hotspot and OpenJ9 and the OpenJ9 support for CircleCI would be simple since AdoptOpenJDK provides builds for them, see: [AdoptOpenJDK API](https://api.adoptopenjdk.net/swagger-ui/#/Assets/get_v3_assets_version__version_).

As an example, the URL of the current JDK image (HotSpot) is: [OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz](https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9/OpenJDK15U-jdk_x64_linux_hotspot_15.0.1_9.tar.gz) 
There is an available OpenJ9 image with the same parameters: [OpenJDK15U-jdk_x64_linux_openj9_15.0.1_9_openj9-0.23.0.tar.gz](https://github.com/AdoptOpenJDK/openjdk15-binaries/releases/download/jdk-15.0.1%2B9_openj9-0.23.0/OpenJDK15U-jdk_x64_linux_openj9_15.0.1_9_openj9-0.23.0.tar.gz)

**Comment by felicianotech** [comment]
Likely waiting on this upstream issue: https://github.com/CircleCI-Public/cimg-shared/issues/51

**Comment by felicianotech** [comment]
For Adoptium, the new home for OpenJDK builds, I'm not seeing Openj9 in the API response or in the archived builds page. Due to that, and this issue being quiet for awhile, we're going to close this. This is something we can revisit in the future if additional builds so up at Adoptium.

**Comment by jonatan-ivanov** [comment]
@felicianotech OpenJ9 was moved out from AdoptOpenJDK (Temurin) but that does not mean it was discontinued, it only means that AdoptOpenJDK does not offer OpenJ9 builds anymore, IBM on the other hand does: it is called [semeru](https://github.com/ibmruntimes?q=semeru&type=all&language=&sort=).

I'm not sure what you mean by "this issue being quiet", this is [your most upvoted issue](https://github.com/CircleCI-Public/cimg-openjdk/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc) ever (as of today), I think people (like me) are waiting for this to be implemented. :)

**Comment by jonatan-ivanov** [comment]
@felicianotech Do you have any thought on my comment above?

**Comment by smlambert** [comment]
FYI, Semeru Open Edition is the same OpenJ9 build that used to be available via AdoptOpenJDK.  In fact we redirect you to the Semeru download page (https://developer.ibm.com/languages/java/semeru-runtimes/downloads/) from the AdoptOpenJDK.net site, and binaries are served up via an API just as the builds from AdoptOpenJDK were. 

See the section regarding OpenJ9 builds in this post: 
https://blog.adoptopenjdk.net/2021/08/goodbye-adoptopenjdk-hello-adoptium/

**Comment by jonatan-ivanov** [comment]
@felicianotech @JalexChen Based on the comment above, could you please reopen this issue?

**Comment by jonatan-ivanov** [comment]
@felicianotech @JalexChen Based on the comment above, could you please reopen this issue? :)

**Comment by jonatan-ivanov** [comment]
@felicianotech @JalexChen Happy new year! Could you please check the comments above? :)

**Comment by jonatan-ivanov** [comment]
It seems closed issues are ignored so let's try this again: https://github.com/CircleCI-Public/cimg-openjdk/issues/225
