### ISSUE TITLE
Add jre versions

### ISSUE THREAD

**Issue by fpopic** [CircleCI-Public/cimg-openjdk#84]
e.g. adoptopenjdk:8-jre
https://github.com/AdoptOpenJDK/openjdk-docker/tree/master/8/jre

**Comment by felicianotech** [comment]
Hi, what's the request here? All of our images includes the JDK, which itself includes the JRE.

**Comment by fpopic** [comment]
to run ci/runtime only jre is needed which reduces the size and time

**Comment by felicianotech** [comment]
Everything in the image is already installed by the time you use it. The size difference would only make spin up time longer by a second or so. With the way our platform caches images on hosts, it'll actually be faster in the long run to have a single image for this.

If you need the JRE, I would just use one of the current OpenJDK images that we have for the version that you need. If you really just want the JRE by itself for some reason, you can also create your own Docker image, based off of the CircleCI Base image (cimg/base) and install the JRE there. Then you can use a smaller image.

At this time we will not be creating a JRE image. If you disagree with this decision, you can always create a new request on [CircleCI Ideas](https://ideas.circleci.com) for JRE only images. If it gets enough votes, we can reconsider this decision.
