### ISSUE TITLE
Add OpenJDK 17 LTS

### ISSUE THREAD

**Issue by cleankod** [CircleCI-Public/cimg-openjdk#94]
The OpenJDK 17 LTS is [generally available](https://jdk.java.net/17/) 🎉  . Please add a corresponding CircleCI node image.

**Comment by felicianotech** [comment]
Will be done soon. 1 blocker: https://github.com/CircleCI-Public/cimg-openjdk/issues/95

**Comment by felicianotech** [comment]
Apologies for the delay. This will be done today.

**Comment by felicianotech** [comment]
OpenJDK v17 is now available.
