### ISSUE TITLE
Likely JAVA_HOME issue

### ISSUE THREAD

**Issue by felicianotech** [CircleCI-Public/cimg-openjdk#95]
There was a report that this envar is set incorrectly. Investigating.

**Comment by diversemix** [comment]
Hey @felicianotech ... is there any update on this?

**Comment by diversemix** [comment]
Take a look at https://github.com/CircleCI-Public/cimg-openjdk/pull/93/files

**Comment by felicianotech** [comment]
Hi. That's not the solution but we're working on it.

**Comment by felicianotech** [comment]
This has been fixed in #98 and #99.
